# Generated by Django 3.0.9 on 2020-09-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='items',
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_v1.Delivery', verbose_name='Поставка'),
        ),
    ]
