# Generated by Django 3.0.9 on 2020-08-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20200727_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='items',
            field=models.ManyToManyField(through='api_v1.DeliveryItem', to='api_v1.Product'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.Delivery', verbose_name='Поставка'),
        ),
    ]
