# Generated by Django 3.0.9 on 2020-09-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20200911_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('a', 'Admin'), ('s', 'Supplier'), ('b', 'Buyer'), ('n', 'None')], default='n', max_length=1),
        ),
    ]
