# Generated by Django 3.0.8 on 2020-09-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20200903_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='api_v1.Category', verbose_name='Категории поставляемых товаров'),
        ),
    ]
